import { Spirit } from '@/entities/spirit';

export const spirits: Spirit[] = [
  {
    id: 'spirit-001',
    name: 'Kitsune',
    threatLevel: 'High',
    location: 'Fushimi Inari Shrine',
    status: 'Active',
  },
  {
    id: 'spirit-002',
    name: 'Tengu',
    threatLevel: 'Critical',
    location: 'Mount Kurama',
    status: 'Active',
  },
  {
    id: 'spirit-003',
    name: 'Kappa',
    threatLevel: 'Medium',
    location: 'Kamo River',
    status: 'Active',
  },
  {
    id: 'spirit-004',
    name: 'Yuki-onna',
    threatLevel: 'High',
    location: 'Snowy Mountains',
    status: 'Captured',
  },
  {
    id: 'spirit-005',
    name: 'Oni',
    threatLevel: 'Critical',
    location: 'Rashomon Gate',
    status: 'Active',
  },
  {
    id: 'spirit-006',
    name: 'Nekomata',
    threatLevel: 'Medium',
    location: 'Old Quarter',
    status: 'Active',
  },
  {
    id: 'spirit-007',
    name: 'Nurikabe',
    threatLevel: 'Low',
    location: 'City Wall',
    status: 'Active',
  },
  {
    id: 'spirit-008',
    name: 'Tsukumogami',
    threatLevel: 'Low',
    location: 'Antique Shop',
    status: 'Captured',
  },
  {
    id: 'spirit-009',
    name: 'Jorōgumo',
    threatLevel: 'High',
    location: 'Jōren Falls',
    status: 'Active',
  },
  {
    id: 'spirit-010',
    name: 'Onibi',
    threatLevel: 'Low',
    location: 'Aokigahara Forest',
    status: 'Active',
  },
  {
    id: 'spirit-011',
    name: 'Rokurokubi',
    threatLevel: 'Medium',
    location: 'Downtown District',
    status: 'Active',
  },
  {
    id: 'spirit-012',
    name: 'Gashadokuro',
    threatLevel: 'Critical',
    location: 'Ancient Battlefield',
    status: 'Active',
  },
  {
    id: 'spirit-013',
    name: 'Bakeneko',
    threatLevel: 'Medium',
    location: 'Temple Garden',
    status: 'Active',
  },
  {
    id: 'spirit-014',
    name: 'Noppera-bō',
    threatLevel: 'Low',
    location: 'Dark Alley',
    status: 'Active',
  },
  {
    id: 'spirit-015',
    name: 'Inugami',
    threatLevel: 'High',
    location: 'Mountain Pass',
    status: 'Active',
  },
  {
    id: 'spirit-016',
    name: 'Ubume',
    threatLevel: 'Medium',
    location: 'Riverside Path',
    status: 'Active',
  },
  {
    id: 'spirit-017',
    name: 'Akaname',
    threatLevel: 'Low',
    location: 'Old Bathhouse',
    status: 'Active',
  },
  {
    id: 'spirit-018',
    name: 'Yama-uba',
    threatLevel: 'Critical',
    location: 'Deep Mountains',
    status: 'Active',
  },
];
